services:
  db:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=dev
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  valkey:
    image: bitnami/valkey:latest
    volumes:
      - ./valkey:/bitnami/valkey/data
    environment:
      - ALLOW_EMPTY_PASSWORD="yes"
      - VALKEY_PASSWORD="dev"
    ports:
      - 6379:6379